### ISSUE TITLE
is there a guide for how to build and deploy this myself?

### ISSUE THREAD

**Issue by lmeninato** [Bryanx/poker#2]

**Comment by Bryanx** [comment]
Hey thanks for your interest in this project. There is no guide for deploying this. This was a school project and although it works I would only use this repo for inspiration if you want to create a Poker app. The core mechanics of Poker are fine and the services are internally connected but were never really fully fleshed out and optimized. 

If you really want to deploy it, here is how we did it:
- The game-service and user-service are Spring Boot projects that were deployed on Heroku Postgress DB.
- The web-client is an Angular 7 project that was also deployed on Heroku.
- We didn't release the Android app to the Play Store.

Some known issues:
- Because a Spring Boot project takes quite some time to build and deploy it's possible Heroku thinks the app is timed out before it can startup. 
- Because a Spring Boot projects takes up a lot of resources it's possible the max is achieved very fastly on Heroku (i think it was about 2GB at the time).

In hindsight, if you want to build a small-scale poker app, it's probably a better idea to build the core services in NodeJS or Ktor as they require much less resources to deploy.

**Comment by lmeninato** [comment]
Thanks for the comprehensive response! I think I'm looking for a more lightweight solution for me and a few friends to play poker with (we would rather host on our own server, since we had some issues with the site we're currently using). Thanks either way!

**Comment by ilya-gorchakov** [comment]
Hello, please help start the server side
